module.exports.addWhiteList = require('./controller.addWhiteList')
module.exports.getWhiteListById = require('./controller.getWhiteListById')
module.exports.listWhiteList = require('./controller.listWhiteList')
module.exports.updateWhiteList = require('./controller.updateWhitelist')
module.exports.removeWhiteList = require('./controller.removeWhiteList')