module.exports.addSeries = require('./controller.addSeries')
module.exports.updateSeries = require('./controller.updateSeries')
module.exports.removeSeries = require('./controller.removeSeries')
module.exports.getSeriesById = require('./controller.getSeriesById')
module.exports.getAllSeries = require('./controller.getAllSeries')
module.exports.getSeriesListByCollectionId = require('./controller.getSeriesListByCollectionId')
