module.exports.addWhiteList = require('./services.addWhiteList')
module.exports.getWhiteListById = require('./services.getWhitelistById')
module.exports.listWhiteList = require('./services.listWhiteList')
module.exports.updateWhiteList = require('./services.updateWhitelist')
module.exports.removeWhiteList = require('./services.removeWhiteList')